manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-nice-oled-zz
      url: https://github.com/zzuse/zmk-nice-oled-zz
      revision: d65bc37d6683a7cea31cbc4b9cb209e00c2b1344
  self:
    path: config
